### ISSUE TITLE
Why not using OpenBB Terminal instead?

### ISSUE THREAD

**Issue by DidierRLopes** [investoreight/i8-terminal#27]
Hey,

I'm behind the team of OpenBB and was wondering why are you building a similar terminal to what we currently have at [OpenBB Terminal](https://github.com/OpenBB-finance/OpenBBTerminal).

Is there anything that our current terminal isn't supporting that you would like us to?

Let me know if you want to have a chat :)

**Comment by investoreight** [comment]
Hi @DidierRLopes. Thanks for your message. i8 Terminal is terminal-based interface and is part of a larger investoreight platform. We indeed see some similarities between the two solutions but we follow a different business model. We will get back to you if necessary.
