### ISSUE TITLE
After successful login there is a message "You need to login"

### ISSUE THREAD

**Issue by SomwareHR** [investoreight/i8-terminal#74]
# Step1 - Login

> user login --terminal

Email: <%MyEmail%>
Password: <%MyPassword%>

`User logged in successfully!`

# Step2 - Get some data

> price list --ticker MSFT

`You need to login before using i8 Terminal. Please login to i8 Terminal using user login command.`

# Misc

+ i8-terminal 0.2.6.2
+ Python 3.10.6
+ Ubuntu 22.04.2 LTS

**Comment by investoreight** [comment]
@SomwareHR Thanks for reporting this. We will look into it. @SaddyHadjigi Can you please check and fix this issue?

**Comment by investoreight** [comment]
@SomwareHR the issue is fixed. Please update the app: `pip install --upgrade i8-terminal`
