### ISSUE TITLE
Fix tagline

### ISSUE THREAD

**Issue by jneidel** [investoreight/i8-terminal#77]
"Modern Market Research with the Power of Command-Line" ->
"Modern Market Research with the Power of **the** Command-Line" or "Modern Market Research **powered by the** Command-Line"

Sounds weird without the "**the**".

Also `i8 --help` still has a different - probably the old - one: "Modern Market Research with the Power of Terminal"

**Comment by investoreight** [comment]
Thanks for your recommendation. We applied your second suggestion :)
