### ISSUE TITLE
Can't `user login`

### ISSUE THREAD

**Issue by jneidel** [investoreight/i8-terminal#79]
`i8 user login` -> `https://investoreight.com/account/authorize?reqId=REQID&redirectUrl=http://localhost:8050`

![screenshot_23-02-25_14:46:43](https://user-images.githubusercontent.com/25589715/221360359-7ec7bcc0-f0d1-464a-b18d-9cd4a29296a1.png)

Authorize redirects to [https://investoreight.com/Home/Error](https://investoreight.com/Home/Error)

The following request hits a 302:

```
POST /Account/authorize HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 294
Content-Type: application/x-www-form-urlencoded
Cookie: COOKIE
Host: investoreight.com
Origin: https://investoreight.com
Pragma: no-cache
Referer: https://investoreight.com/account/authorize?reqId=REQID&redirectUrl=http://localhost:8050
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Sec-GPC: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Brave";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
```

**Comment by investoreight** [comment]
Thanks @jneidel. The issue is now resolved. Please get the latest version of the app.

**Comment by jneidel** [comment]
![screenshot_23-03-20_06:16:58](https://user-images.githubusercontent.com/25589715/226252860-3596b082-bd91-44fb-ab36-07aa6988a959.png)

Different error now...
